openapi: 3.0.3
info:
  title: Payments API documentation
  version: 1.2.1
  termsOfService: https://www.bhimupi.org.in/terms-conditions
  contact:
    name: Koushik
    email: koushik@gmail.com
  
servers:
  - url: http://127.0.0.1:8000
    description: Dev server
  - url: http://10.9.1.2:8080
    description: Prod server
  - url: http://10.8.1.2:9090
    description: UAT server

paths: 
  /apiStatus:
    get:
      responses:
        '200':
          description: A message saying API is up
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: 
                      string
                  rate:
                    type:
                      string
        '404':
          description: A message saying API is down
          content:
            application/json:
              examples:
                api-status-example:
                  value:
                    message: API is down!
        '503':
          description: API is no longer supported

  /payments:
    post:
      responses:
        '200':
          description: Make a payment
          content:
            application/json:
              schema:
                type: object
                properties:
                  amount:
                    type:
                      integer
                    minimum: 0
                    maximum: 100000
                  payer_upi:
                    type:
                      string
                  payee_upi:
                    type:
                      string
                  note:
                    type:
                      string
                  status:
                    type:
                      string
                  timestamp:
                    type:
                      string
              examples:
                txn_1:
                  value:
                    "amount": 130
                    "note": "Books"
                    "payee_upi": "qwe-sbi"
                    "payer_upi": "abx@okhdfc"
                    "status": "initiated"
                    "timestamp": "Tue, 23 Jul 2024 14:16:27 GMT"
                    "transaction_id": "8040cb86-04a2-492b-9b0a-c1b3a450c509"
                txn_2:
                  value:
                    "amount": 300
                    "note": "Ola"
                    "payee_upi": "ankit@okicici"
                    "payer_upi": "abx@okhdfc"
                    "status": "initiated"
                    "timestamp": "Tue, 27 Jul 2024 12:45:27 GMT"
                    "transaction_id": "a5560f7c-123c-46bc-a93f-9ca1ede78957"
                txn_3:
                  value:
                    "amount": 500
                    "note": "Rent"
                    "payee_upi": "abc@okicici"
                    "payer_upi": "xyz@okhdfc"
                    "status": "initiated"
                    "timestamp": "Tue, 31 Jul 2024 12:45:27 GMT"
                    "transaction_id": "30bf4f62-69bd-427a-8974-f2881a061a2b"
                  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                  minimum: 0
                  maximum: 100000
                payer_upi:
                  type: 
                    string
                payee_upi:
                  type: 
                    string
                note:
                  type:
                    string
              additionalProperties: false
              required:
                - amount
                - payer_upi
                - payee_upi
            examples:
                txn_1:
                  value:
                    "amount": 130
                    "note": "Books"
                    "payee_upi": "qwe-sbi"
                    "payer_upi": "abx@okhdfc"
                txn_2:
                  value:
                    "amount": 300
                    "note": "Ola"
                    "payee_upi": "ankit@okicici"
                    "payer_upi": "abx@okhdfc"
                txn_3:
                  value:
                    "amount": 500
                    "note": "Rent"
                    "payee_upi": "abc@okicici"
                    "payer_upi": "xyz@okhd"

  /payments/{transaction_id}:
    put:
      description: Updating a transaction by transaction ID
      parameters:
        - name: transaction_id
          in: path
          required: true
          schema:
            type: 
              string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                  minimum: 0
                  maximum: 100000
                payer_upi:
                  type: 
                    string
                payee_upi:
                  type: 
                    string
                note:
                  type:
                    string
      responses:
        '200':
          description: Successfully updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  amount:
                    type: object
                    properties:
                      amount:
                        type:
                          integer
                      payer_upi:
                        type: 
                          string
                      payee_upi:
                        type: 
                          string
                      note:
                        type:
                          string
                      status:
                        type:
                          string
                      timestamp:
                        type:
                          string
    delete:
      description: deleting a transaction by transaction id
      parameters:
        - name: transaction_id
          in: path
          required: true
          schema:
            type:
              string
      responses:
        '204':
          description: payment is deleted
    get:
      description: gets the transaction details of a particular transaction id
      parameters:
        - name: transaction_id
          in: path
          required: true
          schema:
            type:
              string
      responses:
        '200':
          description: the transaction detials are as follows
          content:
            application/json:
              schema:
                type: object
                properties:
                  amount:
                    type:
                      integer
                  payer_upi:
                    type:
                      string
                  payee_upi:
                    type:
                      string
                  note:
                    type:
                      string
                  status:
                    type:
                      string
                  timestamp:
                    type:
                      string
                  transaction_id:
                    type:
                      string
              examples:
                txn_with_status_initiated:
                  value:
                    "amount": 130
                    "note": "Books"
                    "payee_upi": "qwe-sbi"
                    "payer_upi": "abx@okhdfc"
                    "status": "initiated"
                    "timestamp": "Tue, 23 Jul 2024 14:16:27 GMT"
                    "transaction_id": "8040cb86-04a2-492b-9b0a-c1b3a450c509"
                txn_with_status_cancelled:
                  value:
                    "amount": 300
                    "note": "Ola"
                    "payee_upi": "ankit@okicici"
                    "payer_upi": "abx@okhdfc"
                    "status": "cancelled"
                    "timestamp": "Tue, 27 Jul 2024 12:45:27 GMT"
                    "transaction_id": "a5560f7c-123c-46bc-a93f-9ca1ede78957"
                txn_with_status_successful:
                  value:
                    "amount": 500
                    "note": "Rent"
                    "payee_upi": "abc@okicici"
                    "payer_upi": "xyz@okhdfc"
                    "status": "successful"
                    "timestamp": "Tue, 31 Jul 2024 12:45:27 GMT"
                    "transaction_id": "30bf4f62-69bd-427a-8974-f2881a061a2b"
        '404':
          description: the given transaction is not found

  